<?php
declare(strict_types=1);

// Apimatic SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

ApimaticUtility::setRegistrar(function (ApimaticUtility $u): void {
    $u->clean = [ApimaticClean::class, 'call'];
    $u->done = [ApimaticDone::class, 'call'];
    $u->make_error = [ApimaticMakeError::class, 'call'];
    $u->feature_add = [ApimaticFeatureAdd::class, 'call'];
    $u->feature_hook = [ApimaticFeatureHook::class, 'call'];
    $u->feature_init = [ApimaticFeatureInit::class, 'call'];
    $u->fetcher = [ApimaticFetcher::class, 'call'];
    $u->make_fetch_def = [ApimaticMakeFetchDef::class, 'call'];
    $u->make_context = [ApimaticMakeContext::class, 'call'];
    $u->make_options = [ApimaticMakeOptions::class, 'call'];
    $u->make_request = [ApimaticMakeRequest::class, 'call'];
    $u->make_response = [ApimaticMakeResponse::class, 'call'];
    $u->make_result = [ApimaticMakeResult::class, 'call'];
    $u->make_point = [ApimaticMakePoint::class, 'call'];
    $u->make_spec = [ApimaticMakeSpec::class, 'call'];
    $u->make_url = [ApimaticMakeUrl::class, 'call'];
    $u->param = [ApimaticParam::class, 'call'];
    $u->prepare_auth = [ApimaticPrepareAuth::class, 'call'];
    $u->prepare_body = [ApimaticPrepareBody::class, 'call'];
    $u->prepare_headers = [ApimaticPrepareHeaders::class, 'call'];
    $u->prepare_method = [ApimaticPrepareMethod::class, 'call'];
    $u->prepare_params = [ApimaticPrepareParams::class, 'call'];
    $u->prepare_path = [ApimaticPreparePath::class, 'call'];
    $u->prepare_query = [ApimaticPrepareQuery::class, 'call'];
    $u->graphql_body = [ApimaticGraphql::class, 'body'];
    $u->graphql_errors = [ApimaticGraphql::class, 'errors'];
    $u->result_basic = [ApimaticResultBasic::class, 'call'];
    $u->result_body = [ApimaticResultBody::class, 'call'];
    $u->result_headers = [ApimaticResultHeaders::class, 'call'];
    $u->transform_request = [ApimaticTransformRequest::class, 'call'];
    $u->transform_response = [ApimaticTransformResponse::class, 'call'];
});
